<?php
require_once __DIR__ . '/includes/session.php';
requirePlaybookLogin();
$activePage = 'runs';
$pageTitle = 'Durchführungen';
include __DIR__ . '/includes/header.php';
?>
<section class="page-heading">
    <div><a class="back-link" href="./">Übersicht</a><p class="eyebrow">Konkrete Vorhaben</p><h1>Durchführungen</h1><p class="lead">Ein Playbook anwenden, Eingaben festhalten und Ergebnisdateien erzeugen.</p></div>
    <button id="createRun" class="btn btn-primary" type="button">Durchführung starten</button>
</section>
<section class="filter-bar"><label class="search-field"><span class="sr-only">Durchführungen suchen</span><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg><input id="runSearch" type="search" placeholder="Name oder Template durchsuchen"></label><label class="select-field"><span>Status</span><select id="statusFilter"><option value="">Alle Status</option><option value="draft">Entwurf</option><option value="in_progress">In Arbeit</option><option value="completed">Abgeschlossen</option></select></label><p id="runCount" class="result-count" aria-live="polite">Wird geladen…</p></section>
<section id="runList" aria-live="polite"><div class="skeleton-grid"><i></i><i></i><i></i></div></section>
<dialog id="createRunDialog" class="modal"><form id="createRunForm" class="modal-card"><p class="eyebrow">Neues Vorhaben</p><h2>Durchführung starten</h2><label class="field"><span>Name</span><input id="runName" required maxlength="160" placeholder="z. B. Wetterdaten anbinden"></label><label class="field"><span>Playbook-Template</span><select id="runTemplate" required></select></label><div class="modal-actions"><button type="button" class="btn btn-secondary" data-close>Abbrechen</button><button type="submit" class="btn btn-primary">Starten</button></div></form></dialog>
<script>
(()=>{const list=document.querySelector('#runList'),search=document.querySelector('#runSearch'),filter=document.querySelector('#statusFilter');let runs=[];
const labels={draft:'Entwurf',in_progress:'In Arbeit',completed:'Abgeschlossen'};
async function load(){try{const data=await Playbooks.request('api/runs.php?action=list');runs=data.runs;render();}catch(error){list.innerHTML=`<div class="empty-state"><h2>Laden fehlgeschlagen</h2><p>${Playbooks.escape(error.message)}</p></div>`;}}
function render(){const term=search.value.trim().toLocaleLowerCase('de');const visible=runs.filter(run=>(!filter.value||run.status===filter.value)&&(!term||`${run.name} ${run.template_name}`.toLocaleLowerCase('de').includes(term)));document.querySelector('#runCount').textContent=`${visible.length} von ${runs.length}`;if(!visible.length){list.innerHTML='<div class="empty-state"><h2>Keine Durchführungen gefunden</h2><p>Starte ein Playbook oder passe die Filter an.</p></div>';return;}list.innerHTML=`<div class="template-grid">${visible.map(run=>{const percent=run.phase_count?Math.round(run.completed_count/run.phase_count*100):0;return `<article class="template-card run-card" data-id="${Playbooks.escape(run.id)}"><div class="card-top"><span class="category-chip">${Playbooks.escape(run.template_name)} · v${run.template_version||1}</span><span class="status-dot ${run.status==='completed'?'is-active':''}">${labels[run.status]||run.status}</span></div><div><h2><a href="run.php?id=${encodeURIComponent(run.id)}">${Playbooks.escape(run.name)}</a></h2><p>${run.completed_count} von ${run.phase_count} Phasen · Run v${run.run_version||1}</p></div><div class="progress" aria-label="${percent} Prozent abgeschlossen"><i style="width:${percent}%"></i></div><p class="muted">Aktualisiert ${new Intl.DateTimeFormat('de-DE',{dateStyle:'medium'}).format(new Date(run.updated_at))}</p><div class="card-actions"><a class="btn btn-secondary btn-small" href="run.php?id=${encodeURIComponent(run.id)}">Öffnen</a><button class="icon-btn" data-run-action="duplicate" aria-label="${Playbooks.escape(run.name)} duplizieren">${Playbooks.icon('copy')}</button><button class="icon-btn danger" data-run-action="delete" aria-label="${Playbooks.escape(run.name)} löschen">${Playbooks.icon('trash')}</button></div></article>`}).join('')}</div>`;}
document.querySelector('#createRun').addEventListener('click',async()=>{try{const data=await Playbooks.request('api/templates.php?action=list');const active=data.templates.filter(t=>t.is_active);const select=document.querySelector('#runTemplate');select.replaceChildren(...active.map(t=>new Option(t.name,t.id)));if(!active.length){Playbooks.toast('Es gibt kein aktives Template.','error');return;}document.querySelector('#createRunForm').reset();document.querySelector('#createRunDialog').showModal();document.querySelector('#runName').focus();}catch(error){Playbooks.toast(error.message,'error');}});
document.querySelector('#createRunForm').addEventListener('submit',async event=>{event.preventDefault();event.submitter.disabled=true;try{const data=await Playbooks.request('api/runs.php',{method:'POST',body:JSON.stringify({action:'create',name:document.querySelector('#runName').value,template_id:document.querySelector('#runTemplate').value})});location.href=`run.php?id=${encodeURIComponent(data.id)}`;}catch(error){Playbooks.toast(error.message,'error');event.submitter.disabled=false;}});
document.querySelector('[data-close]').addEventListener('click',()=>document.querySelector('#createRunDialog').close());list.addEventListener('click',async event=>{const button=event.target.closest('[data-run-action]');if(!button)return;const run=runs.find(item=>item.id===button.closest('[data-id]').dataset.id),action=button.dataset.runAction;if(action==='delete'&&!await Playbooks.confirm(`Durchführung „${run.name}“ samt Ergebnisdateien löschen?`,'Durchführung löschen'))return;button.disabled=true;try{await Playbooks.request('api/runs.php',{method:'POST',body:JSON.stringify({action,id:run.id})});Playbooks.toast(action==='delete'?'Durchführung gelöscht.':'Durchführung dupliziert.');await load();}catch(error){Playbooks.toast(error.message,'error');button.disabled=false;}});search.addEventListener('input',render);filter.addEventListener('change',render);load();})();
</script>

<?php include __DIR__ . '/includes/footer.php'; ?>
